---
# Configure Samba account for app user

- name: list samba users
  command: "pdbedit -L"
  register: samba_users

- name: test if app user is in list of samba users
  shell: 'echo "{{ samba_users.stdout }}" | grep -c {{ samba_server_app_user_username }}'
  register: samba_user_app
  ignore_errors: True

- name: if needed create samba account for app user
  raw: 'echo -ne "{{ samba_server_app_samba_user_password }}\n{{ samba_server_app_samba_user_password }}" | smbpasswd -a -s {{ samba_server_app_user_username }}'
  when: samba_user_app.stdout == "0"
